name: koperasi_anggota
description: "Aplikasi Mobile Anggota Koperasi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^6.2.1
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/splash.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/kpu_mart_icon.png"
  min_sdk_android: 21